name: Workflow for dev packages

on:
  pull_request:
    branches: [main]

jobs:
  dev-package-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go 1.21.x ğŸ¹
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Run Unit tests
        run: ./run-test.sh -u
        working-directory: ./scripts

      # - name: Run Integration tests
      #   run: ./run-test.sh -i
      #   working-directory: ./scripts

      # Run static code analysis on source code
      # Run vulnerability scanner and generate SBOMs on third part dependencies
      # # Create build artifacts, e.g. Build docker image with dev tag for applications and push to container registry